# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /shunzi/lsbm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /shunzi/lsbm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /shunzi/lsbm/CMakeFiles /shunzi/lsbm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /shunzi/lsbm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named db_common

# Build rule for target.
db_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_common
.PHONY : db_common

# fast build rule for target.
db_common/fast:
	$(MAKE) -f common/CMakeFiles/db_common.dir/build.make common/CMakeFiles/db_common.dir/build
.PHONY : db_common/fast

#=============================================================================
# Target rules for targets named port

# Build rule for target.
port: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 port
.PHONY : port

# fast build rule for target.
port/fast:
	$(MAKE) -f port/CMakeFiles/port.dir/build.make port/CMakeFiles/port.dir/build
.PHONY : port/fast

#=============================================================================
# Target rules for targets named table

# Build rule for target.
table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 table
.PHONY : table

# fast build rule for target.
table/fast:
	$(MAKE) -f table/CMakeFiles/table.dir/build.make table/CMakeFiles/table.dir/build
.PHONY : table/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f util/CMakeFiles/util.dir/build.make util/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named db_bench

# Build rule for target.
db_bench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_bench
.PHONY : db_bench

# fast build rule for target.
db_bench/fast:
	$(MAKE) -f lsbm/CMakeFiles/db_bench.dir/build.make lsbm/CMakeFiles/db_bench.dir/build
.PHONY : db_bench/fast

#=============================================================================
# Target rules for targets named db_lsmcb

# Build rule for target.
db_lsmcb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 db_lsmcb
.PHONY : db_lsmcb

# fast build rule for target.
db_lsmcb/fast:
	$(MAKE) -f lsbm/CMakeFiles/db_lsmcb.dir/build.make lsbm/CMakeFiles/db_lsmcb.dir/build
.PHONY : db_lsmcb/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... db_common"
	@echo "... port"
	@echo "... table"
	@echo "... util"
	@echo "... db_bench"
	@echo "... db_lsmcb"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

